### PR TITLE
add 4.3.12 to candidate

### PR DESCRIPTION
**Pull request by vfreex**

### CODE REVIEW

**Comment by eparis** [comment]
Don't we put 4.3 candidates into 4.4?

**Comment by sdodson** [comment]
> Don't we put 4.3 candidates into 4.4?

Yes, we should start that now as well as fast-4.4 and stable-4.4 in those PRs. Not sure where to record this so that ART knows to do this going forward.

**Comment by vfreex** [comment]
I didn't notice this change before. Now it is updated.
I will also change our team's procedure docs for awareness.

**Pull request merged**
