### PR TITLE
Add 4.3.9 to fast

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by sdodson** [comment]
/hold
For errata publishing.

**Comment by wking** [comment]
Also blocked on #140.

**Comment by wking** [comment]
We want the edge-blocking #146 to land before this PR, although the timing is otherwise flexible (could be any time between "right now" and "I'm about to approve #142).

**Comment by wking** [comment]
/hold cancel

Errata is public.

```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.3.9-x86_64 | grep errata
    url: https://access.redhat.com/errata/RHBA-2020:0930
```

CI looks good, with everything passing (and a few pending), excepting a number of `...was unreachable during upgrade for at least...`, and #40 has us not blocking edges on that.

**Pull request merged**
