### PR TITLE
channels/*-4.3: Promote 4.2.28 and 4.2.29 to fast/stable regardless of arch

### PR DESCRIPTION
**Pull request by wking**
They went into candidate without architecture qualifiers in 0157b7b6e2 (#229) with an explicit decision to go multi-arch in db17a23add.  But for some reason had arch guards when they went into fast with cb27d438cc (#162) and 9d10713f88 (#178) and stable with 74b433bfca (#163) f652963d12 (#179).

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
> They went into candidate without architecture qualifiers in [0157b7b](https://github.com/openshift/cincinnati-graph-data/commit/0157b7b6e29fb4e5f441276e895ecaaede11733b) (#229) with an explicit decision to go multi-arch in [db17a23](https://github.com/openshift/cincinnati-graph-data/commit/db17a23add816f27e8a6447a0dc8c3fe3b073328). But for some reason had arch guards when they went into fast with [cb27d43](https://github.com/openshift/cincinnati-graph-data/commit/cb27d438ccb796f82d9873dda9227c17ef8c065f) (#162) and [9d10713](https://github.com/openshift/cincinnati-graph-data/commit/9d10713f8831e85d595a639f357aa84859a562f5) (#178) and stable with [74b433b](https://github.com/openshift/cincinnati-graph-data/commit/74b433bfca2221b0cebb2ef53b0aa3d56049d0bd) (#163) [f652963](https://github.com/openshift/cincinnati-graph-data/commit/f652963d126657d2287f588c43c91627071ece6d) (#179).

The decision to go muti-arch #229 was done later i.e. after we merged x86_64 specific edges to fast and stable. ART need to send 3 PRs (i.e. candidate, fast and stable) at one go. so that we do not put ourself in this position again.

**Comment by wking** [comment]
Rebased onto master with 10b2c24 -> 6b94854 to address:

```console
$ hack/stabilization-changes.py
INFO: considering promotions from candidate-4.3 to fast-4.3 after P1W
INFO:   recommended: 4.2.28 (142 days, 7:30:27.122771)
DEBUG:     channels/fast-4.3: Promote 4.2.28 to fast-4.3
DEBUG:     It was promoted the feeder candidate-4.3 by 0d960959e4 (Merge pull request #526 from sdodson/backfill-stable-previous-minors, 2020-11-09).
INFO:   recommended: 4.2.29 (327 days, 3:26:31.122771)
DEBUG:     channels/fast-4.3: Promote 4.2.29 to fast-4.3
DEBUG:     It was promoted the feeder candidate-4.3 by 0157b7b6e2 (Merge pull request #229 from sosiouxme/patch-5, 2020-05-08).
...
```

for #75.

**Pull request merged**
