### PR TITLE
channels: Create stable-4.3 with 4.3.0-x86_64

### PR DESCRIPTION
**Pull request by thiagoalessio**
Related ticket: https://issues.redhat.com/browse/OCPPLAN-2630

### CODE REVIEW

**Comment by eparis** [comment]
This would need to go to candidate-4.3, not stable. the auto updates team, I think, takes the lead getting stuff from candidate to fast/stable.  @LalatenduMohanty @wking is this true?

Also, if there is no s390/powerpc build you can just do 4.3.0, no need for the `-x86_64`.  If there is an s390/powerpc build, which we are trying to intentionally exclude, the format would be `4.3.0+amd64`

**Comment by LalatenduMohanty** [comment]
> This would need to go to candidate-4.3, not stable. the auto updates team, I think, takes the lead getting stuff from candidate to fast/stable. @LalatenduMohanty @wking is this true?

It should first go to the candidates channel then `fast channel` then `stable`

**Comment by sosiouxme** [comment]
Clearly ART docs need updates :)
https://github.com/openshift/cincinnati-graph-data/pull/31 to put it in candidate first.

**Pull request closed without merging**
