### PR TITLE
Add 4.3.9 to candidate

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
Successful upgrades in release controller and I've verified the release is signed properly.

**Comment by vrutkovs** [comment]
* 4.3.5 -> 4.3.9 upgrade on GCP [failed](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/486):

```
E ns/e2e-k8s-service-upgrade-9162 svc/service-test Service is not responding to GET requests over new connections
```

* 4.3.5 and 4.3.8 > 4.3.9 upgrade on Azure [failed](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/114):
```
OpenShift API stopped responding to GET requests: the server is currently unable to handle the request (get imagestreams.image.openshift.io missing)
```

**Comment by wking** [comment]
Need to block 4.2 -> 4.3 for this like #136, right?  Bug is still open in 4.3

**Comment by eparis** [comment]
Do I get candidate-4.4?

**Comment by wking** [comment]
Also, we might want to batch candidate-4.4 addition in here too?  I don't see a reason to split those apart now that we are promoting on a schedule with update monitoring just leading to blocked edges.  Certainly not for candidate promotions.

**Comment by sdodson** [comment]
Yes, we should do candidate-4.4 going forward.
I'm indifferent about blocking edges before we land this into candidate. One side of the coin is that we know we'll be blocking by the time this goes to fast and stable. The other side is we're not getting any early feedback that we regressed something between 4.2.z and 4.3.9 so that we could fix it before 4.3.10. So /shrug

**Comment by eparis** [comment]
/lgtm cancel
add it back when we fix candidate-4.4

**Comment by wking** [comment]
Orthogonal edge-block PR in #146.  If CI passes there, we can land that anytime, even before this PR lands if we want to hide the edge from candidate.  Or we can merge it anytime before #142 lands.

**Comment by sdodson** [comment]
@eparis fixed up

**Pull request merged**
