### PR TITLE
HOSTEDCP-1941: blocked-edges/*HyperShiftNodePoolSkewBinaryDownload: Declare new risk for 4.15.(z>=23) and 4.16.(z>=4)

### PR DESCRIPTION
**Pull request by wking**
Generated by writing the 4.15.23 an 4.16.4 files by hand and copying them out with:

```console
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.15&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]15[.]\(2[4-9]\|[3-9][0-9]\)$' | while read VERSION; do sed "s/4.15.23/${VERSION}/" blocked-edges/4.15.23-HyperShiftNodePoolSkewBinaryDownload.yaml > "blocked-edges/${VERSION}-HyperShiftNodePoolSkewBinaryDownload.yaml"; done
$ curl -s 'https://api.openshift.com/api/upgrades_info/graph?channel=candidate-4.16&arch=amd64' | jq -r '.nodes[] | .version' | grep '^4[.]16[.]\([5-9]\|[1-9][0-9]\)$' | while read VERSION; do sed "s/4.16.4/${VERSION}/" blocked-edges/4.16.4-HyperShiftNodePoolSkewBinaryDownload.yaml > "blocked-edges/${VERSION}-HyperShiftNodePoolSkewBinaryDownload.yaml"; done
```

I'm not aware of PromQL for "what version NodePools are attached to this cluster?", but if that PromQL does exist, it would likely reduce the scope of matching clusters considerably.

### CODE REVIEW

**Comment by wking** [comment]
The impact statement is populated in [HOSTEDCP-1941](https://issues.redhat.com/browse/HOSTEDCP-1941).

/hold cancel

**Comment by wking** [comment]
Testing my regexps:

```console
$ hack/show-edges.py candidate-4.15 | grep ' 4[.]15[.]24' | sort -V
4.14.16 -(risks: HyperShiftKubeAPIPort443, HyperShiftNodePoolSkewBinaryDownload, OVNIPsecPausedMCPConnectivity)-> 4.15.24
...
4.14.33 -(risks: HyperShiftKubeAPIPort443, HyperShiftNodePoolSkewBinaryDownload, OVNIPsecPausedMCPConnectivity)-> 4.15.24
4.15.0 -(risks: HyperShiftKubeAPIPort443, HyperShiftNodePoolSkewBinaryDownload)-> 4.15.24
...
4.15.22 -(risks: HyperShiftNodePoolSkewBinaryDownload)-> 4.15.24
4.15.23 -> 4.15.24
$ hack/show-edges.py candidate-4.16 | grep ' 4[.]16[.]5$' | sort -V
4.15.18 -(risks: HyperShiftNodePoolSkewBinaryDownload)-> 4.16.5
...
4.15.22 -(risks: HyperShiftNodePoolSkewBinaryDownload)-> 4.16.5
4.15.23 -> 4.16.5
4.15.24 -> 4.16.5
4.16.0 -(risks: HyperShiftNodePoolSkewBinaryDownload)-> 4.16.5
...
4.16.3 -(risks: HyperShiftNodePoolSkewBinaryDownload)-> 4.16.5
4.16.4 -> 4.16.5
$ hack/show-edges.py candidate-4.16 | grep ' 4[.]16[.]10$' | sort -V
4.15.18 -(risks: HyperShiftNodePoolSkewBinaryDownload)-> 4.16.10
...
4.15.22 -(risks: HyperShiftNodePoolSkewBinaryDownload)-> 4.16.10
4.15.23 -> 4.16.10
...
4.15.30 -> 4.16.10
4.16.0 -(risks: HyperShiftNodePoolSkewBinaryDownload)-> 4.16.10
...
4.16.3 -(risks: HyperShiftNodePoolSkewBinaryDownload)-> 4.16.10
4.16.4 -> 4.16.10
...
4.16.9 -> 4.16.10
```

**Comment by sdodson** [comment]
/hold
Just an additional vote for waiting to move this forward.

**Pull request merged**
