### PR TITLE
channels/fast-4.2: Promote 4.2.19 (and 4.2.19+amd64 to fast-4.3)

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by vrutkovs** [comment]
/lgtm

@wking seems https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.2.19 has enough tests promote it to fast

**Comment by wking** [comment]
> seems https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.2.19 has enough tests promote it to fast

CI tests are supposed to gate promotion into the candidate channel.  To gate promotion into fast/stable, we want to look at Telemetry/Insights to see if anyone running candidate updates in the wild has hit issues or not.

**Pull request merged**
