### PR TITLE
Add 4.2.25 to fast

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by wking** [comment]
/hold

Landed in candidate [an hour ago][1].  Give it time to cook (and for CI analysis, etc.).

[1]: https://github.com/openshift/cincinnati-graph-data/pull/130#event-3149918682

**Comment by vrutkovs** [comment]
Started few more tests, see https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.2.25

Upgrade failures:
* [4.2.24 -> 4.2.25 AWS](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/22635)
https://bugzilla.redhat.com/show_bug.cgi?id=1731227 CLOSED DEFERRED. Job update tests seem to have flaked due to tuned operator. Not a blocker

Filed https://bugzilla.redhat.com/show_bug.cgi?id=1816150

* [4.2.24 -> 4.2.25 GCP](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/471)

Seems to be a test race, filed https://bugzilla.redhat.com/show_bug.cgi?id=1816194. Not a blocker

* [4.2.21 -> 4.2.25](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/22637) throttling error on setup
* [4.1.38 -> 4.2.25](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/22353) throttling error on setup

/lgtm

**Comment by vrutkovs** [comment]
/cc @eparis 

needs final approve

**Pull request merged**
