### PR TITLE
Adding information why 4.3.2 and 4.3.3 is not in fast,stable 4.3

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by sdodson** [comment]
4.3.4 was never built, but should we add it as well with a reference to https://bugzilla.redhat.com/show_bug.cgi?id=1805726 ?

**Comment by LalatenduMohanty** [comment]
> 4.3.4 was never built, but should we add it as well with a reference to https://bugzilla.redhat.com/show_bug.cgi?id=1805726 ?

https://github.com/openshift/cincinnati-graph-data/pull/88/

**Pull request merged**
