### PR TITLE
add 4.3.12 to stable

### PR DESCRIPTION
**Pull request by vfreex**

### CODE REVIEW

**Comment by wking** [comment]
/hold

Blocked on #168 and cook time.

**Comment by vfreex** [comment]
PR updated.

**Comment by sdodson** [comment]
/assign @wking 
OTA monitor when the 24-48hr fast-to-stable delay ends

**Comment by wking** [comment]
Cook time elapsed.  It was promoted the feeders fast-4.3 and fast-4.4 by a446bfd474 (Merge pull request #167 from vfreex/fast-4.3.12, 2020-04-15).  No new failure modes in Telemetry/Insights in the past 24h.

/hold cancel
/lgtm
/retest

**Pull request merged**
