### PR TITLE
SDN-4481: Set up `NetPolicyTimeoutsHostNetworkedPodTraffic`

### PR DESCRIPTION
**Pull request by petr-muller**
Current understanding of the issue:
- 4.12.48+ _potentially_ affected, so we _may_ block upgrades from all 4.11 and 4.12.x<48
- 4.13.30+ confirmed affected, so we should block upgrades from <4.12.x<48 and k
- 4.14.9+ _potentially_ affected, so we _may_ block upgrades from 4.13.x<30  and 4.14.x<9
- 4.15.0-rc.1+ _potentially_ affected, so we _may_ block upgrades from 4.14.x<9 (I guess we can ignore rc0)
- 4.16.0-ec.0+ _potentially_ affected but there's no relevant unaffected 4.16 or 4.15 so there is nothing to block.

Using PromQL to apply only on clusters that use NetworkPolicy objects.

I have handrafted a file for each minor version and then copied the
rest:

```
$ for fifteen in 2 3 4 5
    cp blocked-edges/4.15.0-rc.1-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml blocked-edges/4.15.0-rc.$fifteen-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
    sed -i -e "s|4.15.0-rc.1|4.15.0-rc.$fifteen|" blocked-edges/4.15.0-rc.$fifteen-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  end

$ for fourteen in 10 11 12
    cp blocked-edges/4.14.9-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml  blocked-edges/4.14.$fourteen-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
    sed -i -e "s|4.14.9|4.14.$fourteen|" blocked-edges/4.14.$fourteen-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  end

$ for thirteen in 31 32 33
    cp blocked-edges/4.13.30-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml  blocked-edges/4.13.$thirteen-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
    sed -i -e "s|4.13.30|4.13.$thirteen|" blocked-edges/4.13.$thirteen-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  end

$ for twelve in 49
    cp blocked-edges/4.12.48-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml  blocked-edges/4.12.$twelve-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
    sed -i -e "s|4.12.48|4.12.$twelve|" blocked-edges/4.12.$twelve-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  end
```

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
Lets drop 4.13.33 from this PR as signatures are missing for this build which is causing the tests to fail.

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
I'm not clear on which clusters have NetworkPolicies, but:

image

is an OCP 4.16.0-ec.2 GCP `TechPreviewNoUpgrade` cluster where the CRD doesn't exist at all understanding that it is not exposed, and:

image

is an OSD 4.15.0-rc.5 AWS cluster where the CRD and some CRs exist understanding that it might be exposed.

**Pull request merged**
