### PR TITLE
Add 4.2.28 to stable

### PR DESCRIPTION
**Pull request by joepvd**

### CODE REVIEW

**Comment by wking** [comment]
/hold

Blocked on #162 and cook time.

**Comment by sdodson** [comment]
/assign @wking 
OTA monitor when the 24-48hr fast-to-stable delay ends

**Comment by wking** [comment]
It was promoted the feeders fast-4.2 and fast-4.3 by 3363c5e425 (Merge pull request #162 from joepvd/4.2.28-fast, 2020-04-14), so cook time has elapsed.  Nothing newly concerning in Telemetry/Insights, so off we go:

/lgtm
/retest

**Pull request merged**
