### PR TITLE
channels/stable-4.7: Populate with 4.6.z from stable-4.6

### PR DESCRIPTION
**Pull request by wking**
Like 1fb8768738 (#585).  Id forgotten to drop 4.6.20 (and its edge to 4.7.1) from stable-4.7 when rebasing 55830fd7f0 (#675), but we're happy with the 4.6->4.7 stability, and ready to put the rest of these in stable-4.7 anyway.

### CODE REVIEW

**Comment by wking** [comment]
#698 will [fix][1]:

```
Error: Error in channel ordering: ["Release 4.6.19 present in stable-4.7, but not in fast-4.7"]
```

/hold

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cincinnati-graph-data/697/pull-ci-openshift-cincinnati-graph-data-master-e2e/1371923593541193728#1:build-log.txt%3A28

**Comment by LalatenduMohanty** [comment]
Now with https://github.com/openshift/cincinnati-graph-data/blame/master/build-suggestions/4.7.yaml#L5  we are good to merge this PR. 
```
default:
  minor_min: 4.6.9999
  minor_max: 4.6.9999
  minor_block_list: []
  z_min: 4.7.9999
  z_max: 4.7.9999
  z_block_list: []
```

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Pull request merged**
