### PR TITLE
candidate-4.3: add 4.3.3

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by wking** [comment]
[publish][1] failed with:

```
error: failed to load configuration: Response from configresolver == 504 (Gateway Timeout)
```

Smells like a CI flake.

/retest

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cincinnati-graph-data/57/pull-ci-openshift-cincinnati-graph-data-master-publish/75

**Comment by wking** [comment]
Waiting on [some CI update jobs][1] to complete...

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.3.3#upgrades-from

**Comment by wking** [comment]
Summarizing [* -> 4.3.3 CI][1]:

* Each baked in update source had at least one green CI run.
* .* -> 4.3.3 shuffles through `aws`, `gcp`, and `azure,mirror` and all of them had at least some passing.  But there are no successful `azure,mirror` on 4.3 -> 4.3.3 and no successful `gcp` on 4.2.20 -> 4.3.3.  Kicking off some more jobs now.
* 4.2.20 -> 4.3.3 has failures for:
    * [AWS failed][2] with:
        ```
        fail [github.com/openshift/origin/test/e2e/upgrade/service/service.go:124]: Feb 19 21:07:31.731: Service was unreachable during upgrade for at least 1m29s:
        ```
        That sounds a bit like [rhbz#1801885][3] and [rhbz#1802246][4] (both `API was unreachable...`), but I don't see an existing bug for `Service was unreachable...`.
    * [AWS failed][5] with:
        ```
        fail [github.com/openshift/origin/test/extended/util/disruption/controlplane/controlplane.go:56]: Feb 19 21:09:59.119: API was unreachable during upgrade for at least 2m47s:
        ```
        That's the two bugs linked above.
    * [AWS failed][6] in setup with:
        ```
        ...listing hosted zones: Throttling: Rate exceeded...
        ```
        That's [rhbz#1767936][7] and the setup-time flake means it's not a 4.3.3 or update issue.
    * [GCP failed][8] with:
        ```
        fail [github.com/openshift/origin/test/extended/util/disruption/controlplane/controlplane.go:56]: Feb 19 20:51:44.664: API was unreachable during upgrade for at least 2m32s:
        ```
        discussed above.  But for GCP, that might also be new symptoms for [rhbz#1793635][9].  Same result in [this other GCP job][10].
    * [GCP failed][11] with:
        ```
        Pools did not complete upgrade: timed out waiting for the condition
        ```
        Mentioned on Azure in [rhbz#1768262][12], but not sure if that's what's going on here.
* 4.3.1 -> 4.3.3 has failures for [AWS][13], Azure][14], and [GCP][15] all failed with:
    ```
    the following tags from the release could not be imported to stable-initial after five minutes...
    ```
    which is a CI-infra flake.
* 4.3.2 -> 4.3.3 has failed for:
    * [Azure failed][16] with platform-throttling at setup-time:
        ```
        level=error msg="Error: Error waiting for Azure Storage Account \"clusterypay8\" to be created: Future#WaitForCompletion: the number of retries has been exceeded: StatusCode=429 -- Original Error: Code=\"TooManyRequests\" Message=\"The request is being throttled as the limit has been reached for operation type - Read. For more information, see - https://aka.ms/srpthrottlinglimits\""
        ```
    * [Azure failed][17] with:
        ```
        fail [github.com/openshift/origin/test/extended/util/disruption/controlplane/controlplane.go:56]: Feb 20 00:01:36.132: API was unreachable during upgrade for at least 2m45s:
        ```
        which is discussed above.

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.3.3#upgrades-from
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18082
[3]: https://bugzilla.redhat.com/show_bug.cgi?id=1801885
[4]: https://bugzilla.redhat.com/show_bug.cgi?id=1802246
[5]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18083
[6]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18084
[7]: https://bugzilla.redhat.com/show_bug.cgi?id=1767936
[8]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/345
[9]: https://bugzilla.redhat.com/show_bug.cgi?id=1793635
[10]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/355
[11]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/357
[12]: https://bugzilla.redhat.com/show_bug.cgi?id=1768262#c1
[13]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18140
[14]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/63
[15]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/356
[16]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/60
[17]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/61

**Comment by wking** [comment]
I'm going to tentatively hang the `...was unreachable during upgrade for at least...` on `Missing CNI default network` and [rhbz#1802246][1].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1802246

**Comment by wking** [comment]
Checking in on the replacement jobs I launched earlier:

* 4.2.20 -> 4.3.3:
    * [GCP][1] failed with:
        ```
        fail [github.com/openshift/origin/test/e2e/upgrade/service/service.go:124]: Feb 20 21:33:12.461: Service was unreachable during upgrade for at least 15m34s:
        ```
    * [GCP][2] failed with:
        ```
        fail [github.com/openshift/origin/test/e2e/upgrade/service/service.go:124]: Feb 20 21:33:06.040: Service was unreachable during upgrade for at least 18m5s:
        ```
    * [GCP][3] failed with:
        ```
        fail [github.com/openshift/origin/test/extended/util/disruption/controlplane/controlplane.go:56]: Feb 20 21:26:33.317: API was unreachable during upgrade for at least 2m24s:
        ```
* 4.3.0 -> 4.3.3:
    * [Azure][5] failed with:
        ```
        fail [github.com/openshift/origin/test/extended/util/disruption/controlplane/controlplane.go:56]: Feb 20 21:43:49.222: API was unreachable during upgrade for at least 3m2s:
        ```
    * [Azure][6] failed with:
        ```
        fail [github.com/openshift/origin/test/extended/util/disruption/controlplane/controlplane.go:56]: Feb 20 21:57:57.456: API was unreachable during upgrade for at least 2m37s:
        ```
* 4.3.1 -> 4.3.3:
    * [Azure][4] failed with:
        ```
        fail [github.com/openshift/origin/test/extended/util/disruption/controlplane/controlplane.go:56]: Feb 20 22:08:17.206: API was unreachable during upgrade for at least 2m32s:
        ```

This is not filling me with confidence in this release ;).

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/364
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/365
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/366
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/66
[5]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/64
[6]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/65

**Comment by wking** [comment]
Ok,  Checking the 4.3->4.3.3 update failures again, they're all on Azure which struggles with slow disks ([rhbz#1798785][1]).  Looking for that in these jobs:

```console
$ # 4.3.0 -> 4.3.3
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/64/build-log.txt | grep -c 'etcdserver: leader changed'
5
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/65/build-log.txt | grep -c 'etcdserver: leader changed'
17
$ # 4.3.1 -> 4.3.3
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/66/build-log.txt | grep -c 'etcdserver: leader changed'
14
$ # 4.3.2 -> 4.3.3
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/61/build-log.txt | grep -c 'etcdserver: leader changed'
16
```

Those numbers aren't higher than normal for Azure, based on the existing examples in the bug.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1798785

**Comment by wking** [comment]
Other bugs turned up during review:

* Turns out `invalid memory address or nil pointer dereference` panics out of the openshift-kube-scheduler-operator pods wasn't actually fixed in 4.3.0, [rhbz#1774212][1].  This is not a regression; the claimed fix had not landed in 4.3 yet.
* `killing connection/stream because serving request timed out and response had been started` panics out of kube-apiserver pods, [rhbz#1807192][2].  Not clear on whether this is a regression or not yet.

Both of those turned up in [the Azure 4.3.2->4.3.3 update job][3].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1774212#c7
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1807192
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/61

**Comment by wking** [comment]
Also some of the nominally-OOMKilled reports discussed in [rhbz#1782601][2].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1782601

**Comment by wking** [comment]
Also for the 4.2 -> 4.3.3 transitions, there's the etcd `tls: bad certificate` flake, [rhbz#1805569][1].

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1805569

**Comment by wking** [comment]
New round of 4.3.2 -> 4.3.3 CI:

* GCP
    * Passed [here][2], [here][4], and [here][7].
    * `API was unreachable during upgrade for at least 2m7s` [here][1].
* AWS
    * Passed [here][5] and [here][6].
    * Died in setup [here][3]

[One AWS job][8] and [three][9] [Azure][10] [jobs][11] are still running.

So summary of 4.3 -> 4.3.3 jobs to date:

* 4.3.2 -> 4.3.3.  11 success (7 AWS, 4 GCP).  1 GCP and one Azure unreachable failure.  1 AWS and one Azure setup-time error (irrelevant to 4.3.3 promotion)
* 4.3.1 -> 4.3.3.  2 success (both AWS).  1 Azure unreachable failure.  3 image-build failures (the following tags from the release could not be imported , irrelevant to 4.3.3 promotion)
* 4.3.0 -> 4.3.3.  1 success (AWS).  2 Azure unreachable failures.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/376
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/377
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18992
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/378
[5]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18993
[6]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18994
[7]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/379
[8]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18991
[9]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/68
[10]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/69
[11]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/70

**Comment by wking** [comment]
4.3.2 -> 4.3.3 Azure jobs back.  [Two][1] [passed][2]; [one][3] died `API was unreachable during upgrade for at least 8m18s` (!).  [The outstanding AWS job][4] is in teardown, but the `test` container completed successfully.  So updated 4.3 -> 4.3.3 jobs to date:

* 4.3.2 -> 4.3.3. 14 success (8 AWS, 4 GCP, 2 Azure). 1 GCP and 2 Azure unreachable failure. 1 AWS and one Azure setup-time error (irrelevant to 4.3.3 promotion)
* 4.3.1 -> 4.3.3. 2 success (both AWS). 1 Azure unreachable failure. 3 image-build failures (the following tags from the release could not be imported , irrelevant to 4.3.3 promotion)
* 4.3.0 -> 4.3.3. 1 success (AWS). 2 Azure unreachable failures.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/70
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/68
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18991

**Comment by sttts** [comment]
Azure job that [died](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/69) has super slow etcd responses around the issue at 21:17.

**Comment by LalatenduMohanty** [comment]
We are still not sure what we should with this PR because of the bugs (as mentioned above comments) found in recent CI testing.

**Comment by sdodson** [comment]
The service and api availability checks are all new tests added in https://github.com/openshift/origin/pull/24479 so it's very hard to compare them to previous results and know whether or not they're regressions.

**Comment by LalatenduMohanty** [comment]
As per the above discussion we expect flakes for gcp, azure. Also this PR is adding the release to candidate. So we should this to candidate and do further testing. 
/lgtm

**Pull request merged**
