### PR TITLE
channels: Promote 4.2.23 to fast-4.2 and fast-4.3

### PR DESCRIPTION
**Pull request by wking**
It was promoted the feeder candidate-4.2 and candidate-4.3 by dc2a3c4cd8 (Merge pull request #115 from joepvd/candidate-4.2.23, 2020-03-13).

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
There is a regression got introduced to 4.2.22 and later builds, see https://github.com/openshift/cincinnati-graph-data/pull/125 , I would suggest that we drop this build and add the build with the fix.

**Comment by wking** [comment]
/hold

We might want to tombstone this instead because of #125.

**Comment by wking** [comment]
I'm just going to close this.  I'll file a tombstoning PR in a bit.

/close

**Comment by wking** [comment]
Tombstoned in #127.

**Pull request closed without merging**
