### PR TITLE
Add 4.2.25 to stable

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by wking** [comment]
/hold

Blocked on #131

**Comment by vrutkovs** [comment]
/hold cancel
/lgtm

fast-4.3 PR merged

**Comment by wking** [comment]
[publish][1]:

```
urllib2.HTTPError: HTTP Error 429: Too Many Requests
```

Just Quay falling over.

/retest

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cincinnati-graph-data/132/pull-ci-openshift-cincinnati-graph-data-master-publish/247

**Comment by wking** [comment]
/hold

#131 only landed ~30m ago.  We should wait longer than that before promoting to stable to avoid a rush on the migrations.

**Comment by vrutkovs** [comment]
Telemetry data shows that:
* ~40 clusters updated to 4.2.25, no issues found
* ~20 clusters are running .25 now

I suppose its good for stable.

/cc @eparis

**Pull request merged**
