### PR TITLE
prerelease-4.1: add 4.1.37

### PR DESCRIPTION
**Pull request by vfreex**

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

CI data at https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.1.37 shows 5/7 updates have failed

**Comment by vrutkovs** [comment]
Filed https://bugzilla.redhat.com/show_bug.cgi?id=1810480. Although this test fails often during upgrade (70% of cases) its has been plaguing previous releases too - 57% of upgrades in 4.1.31

**Comment by vrutkovs** [comment]
/approve
/lgtm

Known issue, most likely would be wontfixed by api-server team.

/cc eparis

Feel free to cancel the hold when ready

**Comment by LalatenduMohanty** [comment]
https://github.com/openshift/cincinnati-graph-data/pull/98/ Adding 4.1.37 to candidate 4.2 channel

**Pull request merged**
