### PR TITLE
`{eus,stable}-4.12`: Add 4.11 ⟶ 4.12 edges

### PR DESCRIPTION
**Pull request by petr-muller**
Generated with:

```console
$ ./hack/release-stable-minor.sh 4.12
```

The script also generated the following changes which I believe will merge separately by automation so I omitted them from the PR:

```diff
diff --git a/channels/fast-4.12.yaml b/channels/fast-4.12.yaml
index 4bbf08e4..6bcdef43 100644
--- a/channels/fast-4.12.yaml
+++ b/channels/fast-4.12.yaml
@@ -43,3 +43,4 @@ versions:
 - 4.12.7
 - 4.12.8
 - 4.12.9
+- 4.12.10
diff --git a/internal-channels/stable.yaml b/internal-channels/stable.yaml
index 07afa19a..16adcdf3 100644
--- a/internal-channels/stable.yaml
+++ b/internal-channels/stable.yaml
@@ -322,3 +322,4 @@ versions:
 - 4.12.6
 - 4.12.7
 - 4.12.8
+- 4.12.9
```

### CODE REVIEW

**Comment by sdodson** [comment]
/lgtm
still needed that

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Pull request merged**
