### PR TITLE
OTA-1297: blocked-edges: Declare TechPreviewSignatureStoresInDefault for 4.16.0-rc.3 and later

### PR DESCRIPTION
**Pull request by wking**

### CODE REVIEW

**Comment by wking** [comment]
Confirming a `TechPreviewNoUpgrade` standalone cluster ([build02][]) knows it's not exposed:

image

And a standalone default-feature-set cluster ([build01][]) knows it is exposed:

image

Hunting for a hosted/HyperShift cluster...

[build01]: https://console.build01.ci.openshift.org/
[build02]: https://console.build02.ci.openshift.org/

**Comment by wking** [comment]
Cluster Bot `launch 4.16.0-rc.2` doesn't seem to have `cluster_feature_set` or `cluster_installer`.  Here's some new PromQL in that hosted cluster, showing it realizing it's not affected:

image

Build01 (standalone, default feature set) knows it is affected:

image

Build02 (standalone, `TechPreviewNoUpgrade`) knows it's not affected:

image

**Comment by wking** [comment]
Actually, never mind about the HyperShift testing.  [This HyperShift code][1] shows `cluster_installer` being preserved, so it must be in some kind of management-cluster-side PromQL store, even though it's not available hosted-side (because the CVO is not available hosted-side to get scraped).  I'm fine with my current fe271f8aebf3066 PromQL again.

[1]: https://github.com/openshift/hypershift/blob/ddc14f78002544875fb357037d0757798da7db37/support/metrics/sets.go#L118

**Review by PratikMahajan — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
I dunno what's up with [the signature 404s][1], but it's not related to this pull, which declares risks for existing releases, and is not adding new releases.

/override ci/prow/e2e

[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cincinnati-graph-data/5370/pull-ci-openshift-cincinnati-graph-data-master-e2e/1800228767705075712#1:build-log.txt%3A50

**Comment by wking** [comment]
Turns out 4.17.0-ec.0 isn't signed yet, and hasn't entered the `candidate` channel, so the e2e failures were real.  I've dropped it for now, and we can re-declare that risk after it's in the `candidate` channel, before it enters `candidate-4.17`.

**Pull request merged**
