### PR TITLE
Add 4.3.13 to candidate

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by wking** [comment]
[CI][1] is having throughput issues.  For example, [all][2] [four][3] [of][4] [the][5] 4.3.9 jobs died on either AWS throttling or Boskos lease exhaustion (which is designed to protect us from excessive AWS throttling).  We have had a few update-time failures, so far all on 4.3->4.3.13 GCP for `...unreachable during disruption...`: [4.3.1][8], [4.3.5][6], and [4.3.10][7], but we don't block promotion on that.  Will wait to see some success for 4.2 -> 4.3.13...

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.3.13#upgrades-from
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/25795
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/25810
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/25824
[5]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/25836
[6]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/593
[7]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/594
[8]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/592

**Comment by wking** [comment]
[Success][1] [from][2] 4.2.  So I'm fine with this happening whenever ART is happy with the release state.

/hold

ART, pull the hold whenever you're ready.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/25835
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/25834

**Comment by sosiouxme** [comment]
/hold cancel
Release is accepted now and looks like @thiagoalessio did manually the parts that the release job failed on.

**Comment by wking** [comment]
/lgtm

Looks like I forgot to approve earlier.

**Comment by wking** [comment]
/hold cancel

Never mind, just had a little freak-out about this not being in candidate-4.4, but it's there ;).

**Pull request merged**
