### PR TITLE
channels: Promote 4.2.23 to stable-4.2 and stable-4.3

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by wking** [comment]
Blocked on #121

**Comment by LalatenduMohanty** [comment]
There is a regression got introduced to 4.2.22 and later builds, see https://github.com/openshift/cincinnati-graph-data/pull/125 , I would suggest that we drop this build and add the build with the fix.

**Comment by wking** [comment]
I'm just going to close this.  I'll file a tombstoning PR in a bit.

/close

**Comment by wking** [comment]
Tombstoned in #127.

**Pull request closed without merging**
