### PR TITLE
add rc.1 in candidate-4.4.yaml

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by wking** [comment]
No need for a new 4.3 release, because we already have 4.3.5 in this channel, and:

```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.4.0-rc.1-x86_64 | grep Upgrades
  Upgrades: 4.3.5, 4.4.0-rc.0
```

Single [AWS rc.0 -> rc.1][1] update passed.  Looking at the 4.3.5 -> rc.1 jobs, three AWS jobs passed, [one][2] failed on setup (throttling), and [one][3] had short (<2m) `unreachable during disruption` issues.  None of those are candidate-promotion blockers.

I'll launch some CI jobs on GCP and Azure...

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/21327
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/21349
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/21327

**Comment by wking** [comment]
New results:

* [4.3.5 -> 4.4.0-rc.1 GCP][1] failed with some `unreachable during disruption`,  all less that 4m, which we don't consider edge-blocking.
* [4.3.5 -> 4.4.0-rc.1 GCP][2] failed with `Cluster did not complete upgrade: timed out waiting for the condition: Working towards 4.4.0-rc.1: 12% complete`.  Needs more investigation.
* [4.3.5 -> 4.4.0-rc.1 Azure][3] failed with `failed to acquire lease: status 503 Service Unavailable`, which is pre-update, so no impact on edge stability.
* [4.3.5 -> 4.4.0-rc.1 Azure][4] failed with `Cluster did not complete upgrade: timed out waiting for the condition: Working towards 4.4.0-rc.1: 18% complete`.  Needs more investigation.
* [4.4.0-rc.0 -> 4.4.0-rc.1 GCP][5] failed with `failed to acquire lease: status 503 Service Unavailable`.
* [4.4.0-rc.0 -> 4.4.0-rc.1 Azure][6] had some `unreachable during disruption`, all less than 2m, and was counted as a success.

Launching replacements for the two Boskos 503s...

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/442
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/443
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/91
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/92
[5]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/445
[6]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/93

**Comment by wking** [comment]
[The 4.3.5 -> 4.4.0-rc.1 GCP timeout job][1] has:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/443/artifacts/e2e-gcp-upgrade/must-gather/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-f1ffcdcbd684afd61ff1874b47e1c61a0f7adab93b7a21123a1e29b041d3dabf/namespaces/openshift-cluster-version/pods/cluster-version-operator-5fffc549d9-shbf9/cluster-version-operator/cluster-version-operator/logs/current.log | grep 'Running sync.*in state\|Result of work' | tail -n4
2020-03-13T22:46:45.34504345Z I0313 22:46:45.345010       1 task_graph.go:596] Result of work: [Cluster operator etcd is reporting a failure: EtcdMemberIPMigratorDegraded: etcdserver: Peer URLs already exists]
2020-03-13T22:49:55.347779833Z I0313 22:49:55.347709       1 sync_worker.go:471] Running sync registry.svc.ci.openshift.org/ocp/release@sha256:6fa3e6520d6668737d29a68ef7d7189642b07dba9b17511316210f336e9492b0 (force=true) on generation 2 in state Updating at attempt 8
2020-03-13T22:55:40.40044101Z I0313 22:55:40.399557       1 task_graph.go:596] Result of work: [Cluster operator etcd is reporting a failure: EtcdMemberIPMigratorDegraded: etcdserver: Peer URLs already exists]
2020-03-13T22:58:57.58632797Z I0313 22:58:57.586215       1 sync_worker.go:471] Running sync registry.svc.ci.openshift.org/ocp/release@sha256:6fa3e6520d6668737d29a68ef7d7189642b07dba9b17511316210f336e9492b0 (force=true) on generation 2 in state Updating at attempt 9
```

[The Azure job][2] has:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/92/artifacts/e2e-azure-upgrade/must-gather/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-69d0187ff513f67a3dbe37c843e318a59ff27699f3c38dcd2d79df13bc176def/namespaces/openshift-cluster-version/pods/cluster-version-operator-5fffc549d9-kmq5k/cluster-version-operator/cluster-version-operator/logs/current.log | grep 'Running sync.*in state\|Result of work' | tail -n3
2020-03-13T23:01:42.3198065Z I0313 23:01:42.319768       1 task_graph.go:596] Result of work: [Cluster operator kube-controller-manager is reporting a failure: NodeInstallerDegraded: 1 nodes are failing on revision 346:
2020-03-13T23:04:40.0548178Z I0313 23:04:40.054748       1 sync_worker.go:471] Running sync registry.svc.ci.openshift.org/ocp/release@sha256:6fa3e6520d6668737d29a68ef7d7189642b07dba9b17511316210f336e9492b0 (force=true) on generation 2 in state Updating at attempt 9
2020-03-13T23:10:25.1064177Z I0313 23:10:25.106409       1 task_graph.go:596] Result of work: [Cluster operator kube-controller-manager is reporting a failure: NodeInstallerDegraded: 1 nodes are failing on revision 393:
```

I'll hunt around for 4.3 -> 4.4 bugs mentioning `EtcdMemberIPMigratorDegraded` from `etcd` or `NodeInstallerDegraded` from `kube-controller-manager`.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/443
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/92

**Comment by wking** [comment]
`EtcdMemberIPMigratorDegraded: etcdserver: Peer URLs already exists` is [rhbz#1811706][1].  I've asked the etcd team for an impact statement.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1811706

**Comment by wking** [comment]
Created [rhbz#1813512][1] for the `NodeInstallerDegraded`.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1813512

**Comment by wking** [comment]
[4.3.5 -> 4.4.0-rc.1 Azure][1] died in setup with `ReferencedResourceNotProvisioned`, [rhbz#1813513][1].  I've launced a replacement.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1813513

**Comment by wking** [comment]
[4.4.0-rc.0 -> 4.4.0-rc.1 GCP][1] had some `unreachable during disruption`, all less than 2m, and was counted as a success.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/447

**Comment by wking** [comment]
[4.3.5 -> 4.4.0-rc.1 Azure][1] failed with `Cluster did not complete upgrade: timed out waiting for the condition: Working towards 4.4.0-rc.1: 12% complete` with the `EtcdMemberIPMigratorDegraded: etcdserver: Peer URLs already exists` issue from [rhbz#1811706](https://bugzilla.redhat.com/show_bug.cgi?id=1811706).  We may want to get that triaged before we add rc.1 to candidate-4.4.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/95

**Comment by wking** [comment]
My EtcdMemberIPMigratorDegraded bug was closed as a dup of [rhbz#1812584][1], which is VERIFIED today.  So I'd guess the next RC will have the fix.  I'm agnostic about whether we pull 4.3 -> 4.4 edges for the current 4.4 RCs from candidate-4.4 or not.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1812584

**Comment by wking** [comment]
I haven't mentioned the NodeInstallerDegraded job in the past few comments, but [preliminary noises][1] from @tnozicka make it sound like a potential upgrade blocker as well.  Still not clear on whether it's common enough to call for excluding rc.1 from candidate-4.4 .

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1813512#c1

**Comment by eparis** [comment]
What do we think about merging this, then pull edges when the next rc comes along with a note to 1812584?

**Comment by sdodson** [comment]
> What do we think about merging this, then pull edges when the next rc comes along with a note to 1812584?

That's fine, I was hoping that there'd be a new RC first thing this morning but there isn't.

**Comment by LalatenduMohanty** [comment]
Right we should be fine to merge this as we know what are the issues around this RC. 
/lgtm

**Comment by LalatenduMohanty** [comment]
Created https://github.com/openshift/cincinnati-graph-data/pull/123/

**Comment by wking** [comment]
/hold

rc.1 may be impacted by #125.  Let's keep it out of channels until we know for sure.  See also the bugs linked from #123.

**Comment by wking** [comment]
Tombstoned in #127.

/close

**Comment by LalatenduMohanty** [comment]
/reopen 
As we do not hold the PR in candidates because of upgrade blockers.

**Comment by LalatenduMohanty** [comment]
@sosiouxme Can you reopen the PR please?

**Comment by wking** [comment]
/close

Getting handled in #127 (although that's now adding to candidate, but with different motivation)

**Pull request closed without merging**
