### PR TITLE
candidate-4.3: add 4.3.2

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by eparis** [comment]
/approve
/hold
Holding for ota

**Comment by vrutkovs** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1802710 is affecting 4.2 -> 4.3 upgrades, I'd rather hold it off for now

**Comment by wking** [comment]
Summarizing [the * -> 4.3.2 CI failures][1]:

* [All][2] [of][3] [the][4] [4.3.1][5] failures were `...failed to update lease ...: status 503 Service Unavailable...` Boskos flakes.
* [The 4.2.19 GCP failure][6] was:
    ```
    fail [k8s.io/kubernetes/test/e2e/framework/service/jig.go:915]: Feb 13 19:21:41.157: Could not reach HTTP service through 104.196.184.34:80 after 2m0s
    ```
    which is [rhbz#1793635][7], discussed in #40.

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.3.2#upgrades-from
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/17846
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/17848
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/49
[5]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/335
[6]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/328
[7]: https://bugzilla.redhat.com/show_bug.cgi?id=1793635

**Pull request merged**
