### PR TITLE
Add 4.2.21 to stable

### PR DESCRIPTION
**Pull request by joepvd**
Note, there might be legit concerns to add the upgrade path to `stable-4.3`.

### CODE REVIEW

**Comment by sdodson** [comment]
Yeah, can you please split the two changes into different PRs?

**Comment by sdodson** [comment]
/hold
Need to split stable-4.3 addition of 4.2 versions for now.

**Comment by LalatenduMohanty** [comment]
> Need to split stable-4.3 addition of 4.2 versions for now.

+1

**Comment by sdodson** [comment]
/close
I'll split this

**Pull request closed without merging**
