### PR TITLE
blocked-edges/4.7: Block all 4.6 edges to 4.7.4

### PR DESCRIPTION
**Pull request by jottofar**

### CODE REVIEW

**Comment by wking** [comment]
We have a 4.7.4 image now.

/retest

**Comment by jottofar** [comment]
looks like we're waiting on signatures now

**Comment by wking** [comment]
/retest

https://amd64.ocp.releases.ci.openshift.org/releasestream/4-stable/release/4.7.4 has been accepted, so we should have sigs.

**Comment by wking** [comment]
Even if we don't have sigs yet, retest bot should bang away until it sees them:

/hold cancel

**Pull request merged**
