### PR TITLE
candidate-4.3: Add 4.3.5

### PR DESCRIPTION
**Pull request by joepvd**

### CODE REVIEW

**Comment by vrutkovs** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/20280
4.2.22 -> 4.3.5 upgrade fails 'cause samples operator is progressing

**Comment by vrutkovs** [comment]
https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/404
4.3.2 -> 4.3.5 update on GCP

image-registry, ingresscontroller, monitoring degraded

**Comment by gabemontero** [comment]
> https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/20280
> 4.2.22 -> 4.3.5 upgrade fails 'cause samples operator is progressing - seems to be a flake

Yep looks like we have a timing bug where if an samples imagestream was totally deleted from OCP (the EAP folks look to have done this between 4.2 and 4.5), we can end up in a state where we have stale entries in our progressing list.

Such was the case with guys like `rhdm73-decisioncentral-openshift`

Whether it hits us or not could depend to some degree on when imports come in on the upgrade, so this would explain why @vrutkovs did not see this in all his upgrades.

I've opened https://bugzilla.redhat.com/show_bug.cgi?id=1811143 against 4.4 (still no 4.5 target yet) 
and will start cloning as needed.

I believe I have a handle on the fix.

**Comment by gabemontero** [comment]
> > https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/20280
> > 4.2.22 -> 4.3.5 upgrade fails 'cause samples operator is progressing - seems to be a flake
> 
> Yep looks like we have a timing bug where if an samples imagestream was totally deleted from OCP (the EAP folks look to have done this between 4.2 and 4.5), we can end up in a state where we have stale entries in our progressing list.
> 
> Such was the case with guys like `rhdm73-decisioncentral-openshift`
> 
> Whether it hits us or not could depend to some degree on when imports come in on the upgrade, so this would explain why @vrutkovs did not see this in all his upgrades.
> 
> I've opened https://bugzilla.redhat.com/show_bug.cgi?id=1811143 against 4.4 (still no 4.5 target yet)
> and will start cloning as needed.
> 
> I believe I have a handle on the fix.

https://github.com/openshift/cluster-samples-operator/pull/240 is up on samples operator master branch

**Comment by sdodson** [comment]
/lgtm
This should be fine for candidate.

**Pull request merged**
