### PR TITLE
candidate-4.3: add 4.3.1

### PR DESCRIPTION
**Pull request by sosiouxme**

### CODE REVIEW

**Comment by wking** [comment]
Do we also want to add the 4.2 update source?  Looks like that's 4.2.18:

```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.3.1-x86_64 | grep Upgrades
  Upgrades: 4.2.18, 4.3.0-rc.0, 4.3.0-rc.3, 4.3.0
```

I'm also fine if we want to punt putting 4.2.18 into candidate-4.3 to a separate PR.

**Comment by vrutkovs** [comment]
>Do we also want to add the 4.2 update source? 

I don't think we had sufficient amount of upgrades in `fast-4.3` for that yet

**Comment by wking** [comment]
Looking through [our CI updates][1], everything looks good except for:

* The known GCP issue (which [hit 4.2.18 -> 4.3.1][2] and which we are ok allowing in Cincinnati anyway, #40.
* [A `Could not update deployment "openshift-kube-scheduler-operator/openshift-kube-scheduler-operator" (81 of 494)` failure on Azure][3], which I'm still triaging.

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.3.1#upgrades-from
[2]: https://bugzilla.redhat.com/show_bug.cgi?id=1785457#c22
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/39#1:build-log.txt%3A1148

**Comment by wking** [comment]
Azure failure was probably due to slow disks.  Tracked in [rhbz#1798785][1].  That's neither new nor update-specific, so my only remaining concerns with this channel promotion are:

* It does not promote 4.2.18 yet.
* Our [4.2.18 rename failed promotion][2].

Once we get the story around 4.2.18's existence straightened out, the update folks are fine with this.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1798785
[2]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.2.18

**Comment by wking** [comment]
[All][1] [three][2] [replacement][3] 4.2.18 -> 4.3.1 Azure jobs passed, so that's a good sign too.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/40
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/41
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/42

**Comment by sosiouxme** [comment]
going to retry 4.2.18
I was thinking that when a release's promotion is successful, that's when we would add a PR just for that release (so in this case, once 4.2.18 is accepted, add it to candidate-4.2 and candidate-4.3). Makes our logic simpler not to have to think about multiple releases. Can OTA just add blocked edges to our PRs as they see fit?

**Comment by LalatenduMohanty** [comment]
> Can OTA just add blocked edges to our PRs as they see fit?

OTA wont be merging any PRs as it is up to the release admins. But OTA would provide info with respect to, if the edge looks stable enough by looking in to telemetry dash boards and CI results.

**Comment by wking** [comment]
> Can OTA just add blocked edges to our PRs as they see fit?

I've pushed 060341c -> 9c77b39 to your branch for this PR blocking 4.2.18->4.3.1 until we have a 4.2.18 to consider.  Generated with:

```console
$ git remote add sosiouxme ssh://github.com/sosiouxme/cincinnati-graph-data.git
$ git fetch sosiouxme
$ git checkout sosiouxme/patch-3
$ emacs blocked-edges/4.3.1.yaml  # manually fill this in
$ git add blocked-edges/4.3.1.yaml
$ git commit -v
$ git push sosiouxme HEAD:patch-3
```

**Pull request merged**
