### PR TITLE
Adding 4.1.37 to candidate-4.2

### PR DESCRIPTION
**Pull request by LalatenduMohanty**
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>

### CODE REVIEW

**Comment by vrutkovs** [comment]
Started a few 4.1.37 -> 4.2 updates

**Comment by LalatenduMohanty** [comment]
> Started a few 4.1.37 -> 4.2 updates

**Comment by LalatenduMohanty** [comment]
Mistakenly closed it.

**Comment by vrutkovs** [comment]
/lgtm

6 upgrade tests for 4.1.37 -> 4.2.20 / 4.2.21 / 4.2.22 passed, see https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.1.37

/cc @eparis

**Pull request merged**
