### PR TITLE
channels/fast-4.3: Promote 4.3.2

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by vrutkovs** [comment]
Starter clusters have encountered node issues on 4.3.2 update

**Comment by vrutkovs** [comment]
Starter cluster have hit a few issues:
* us-east2 was a false alarm - a new crashlooping pod has been started in `openshift-*` namespace and thus triggered KubePodCrashLooping alert
* us-east1 had two nodes stuck - one was unresponsive, the other one had several important services restarting.

@bradmwilliams any update on us-east-1 starter cluster situation?

**Comment by bradmwilliams** [comment]
> Starter cluster have hit a few issues:
> 
> * us-east2 was a false alarm - a new crashlooping pod has been started in `openshift-*` namespace and thus triggered KubePodCrashLooping alert
> * us-east1 had two nodes stuck - one was unresponsive, the other one had several important services restarting.
> 
> @bradmwilliams any update on us-east-1 starter cluster situation?

@vrutkovs There are 2 **4.3.2** starter clusters (us-east-1 and us-west-1).  Both have been struggling with nodes falling into NotReady states and ultimately resulting in multiple degraded operators.  It is possible to manually combat the NotReady nodes by power cycling, in the AWS Console, the nodes, but inevitably it turns into a game of whack-a-mole.  Eventually, the operators catch up and things resume operating as usual, but only for a short period of time.  There definitely seems to be some correlation between the impacted node and the prometheus-k8s pods in the openshift-monitoring namespace.  The only other information that I have is prior to the node loosing SSH connectivity, there are multiple system service failures on the node:

```
[systemd]
Failed Units: 6
  chronyd.service
  irqbalance.service
  polkit.service
  rhsmcertd.service
  rpc-statd.service
  sssd.service
```
I have also observed that the prometheus alerts api appears to be not functioning any longer.  Code that worked previously, now simply returns a 503.

**Comment by LalatenduMohanty** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1794142 and https://bugzilla.redhat.com/show_bug.cgi?id=1805444  are the blocker bugs  for 4.3.2. Hence we should not allow 4.3.2 in to fast-4.3

**Comment by LalatenduMohanty** [comment]
#87 supersedes this.

**Pull request closed without merging**
