### PR TITLE
graph-data.rs: sync Cincinnati with prod commit

### PR DESCRIPTION
**Pull request by vrutkovs**
Ensure that latest cincinnati-graph-data is compatible with production Cincinnati, as agreed in https://hackmd.io/YoAQ5IkzQoSWqZMcDqPxAQ?edit

### CODE REVIEW

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by vrutkovs** [comment]
/hold

Still no luck fetching image from the registry

**Pull request merged**
