### PR TITLE
Add 4.2.21 to fast channels

### PR DESCRIPTION
**Pull request by joepvd**

### CODE REVIEW

**Comment by LalatenduMohanty** [comment]
We had found two issues while adding it to candidate channel
```

    https://bugzilla.redhat.com/show_bug.cgi?id=1734524 marked UpgradeBlocker
    https://bugzilla.redhat.com/show_bug.cgi?id=1809259

```

https://github.com/openshift/cincinnati-graph-data/pull/81

**Comment by sdodson** [comment]
My opinion is that we shouldn't block on either of those.

**Comment by sdodson** [comment]
/hold cancel
:shipit:

**Pull request merged**
