### PR TITLE
channels/stable-4.2: 4.2.19 to stable

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by wking** [comment]
/hold

Blocked on fast in #64

**Comment by eparis** [comment]
does it belong in stable-4.3?

**Comment by vrutkovs** [comment]
Blocked by https://github.com/openshift/cincinnati-graph-data/pull/64 (`fast-4.2`)

**Comment by eparis** [comment]
/approve cancel
I think this should go into stable-4.3 at the same time

**Comment by LalatenduMohanty** [comment]
#64 is merged now. @thiagoalessio Can you rebase this PR?

**Comment by LalatenduMohanty** [comment]
@eparis It is in https://github.com/openshift/cincinnati-graph-data/blob/master/channels/fast-4.3.yaml#L8 but not in stable-4.3 as we do not have any 4.2 release in stable-4.3

**Comment by eparis** [comment]
Why are there no 4.2 releases in 4.3-stable?

**Comment by LalatenduMohanty** [comment]
> Why are there no 4.2 releases in 4.3-stable?

We have not enabled edges in stable because of https://github.com/openshift/cincinnati-graph-data/blob/master/blocked-edges/4.3.0.yaml#L4

**Pull request merged**
