### PR TITLE
Add 4.2.24 to candidate

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by wking** [comment]
[Update CI][1] only has two jobs, so a bunch of the baked-in update sources are untested, and we have no CI yet for GCP or Azure.

```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.2.24-x86_64 | grep Upgrades
  Upgrades: 4.1.38, 4.2.14, 4.2.15, 4.2.16, 4.2.18, 4.2.19, 4.2.20, 4.2.21, 4.2.22, 4.2.23
```

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.2.24#upgrades-from

**Comment by LalatenduMohanty** [comment]
There is a regression got introduced to 4.2.22 and later https://github.com/openshift/cincinnati-graph-data/pull/125 , I would suggest that we drop this build and add the build with the fix.

**Comment by wking** [comment]
/close

I'll roll this into my tombstone PR.

**Comment by wking** [comment]
Tombstoned in #127.

**Pull request closed without merging**
