### PR TITLE
Add 4.3.10 to fast

### PR DESCRIPTION
**Pull request by joepvd**

### CODE REVIEW

**Comment by wking** [comment]
/hold

Need #153 to land and cook first.

**Comment by wking** [comment]
Needs a rebase.

[CI analysis][1]:

* 4.2.21 Failed: 1 AWS ([`unreachable during disruption`][2]).
* 4.2.22 Pending: 1 GCP ([CI just forgot about this job][3]). Failed: 1 GCP ([CI registry flake][4]).
* 4.2.23 Failed: 1 Azure ([`Cluster operator monitoring is still updating`][5]).
* 4.2.25 Failed: 1 AWS ([CI registry flake][6]).
* 4.2.26 Failed: 1 AWS ([`unreachable during disruption`][7]), 1 GCP ([`unreachable during disruption`][8]).
* 4.2.27 Failed: 1 Azure ([`Cluster operator monitoring is still updating`][9]).
* 4.3.0 Failed:	1 AWS ([`unreachable during disruption`][10]).
* 4.3.1 Success: 1 GCP.
* 4.3.2 Success: 1 Azure.
* 4.3.3 Success: 1 AWS.
* 4.3.5 Failed:	1 GCP ([`unreachable during disruption`][11]).
* 4.3.8 Success: 1 Azure.
* 4.3.9 Success: 2 AWS.

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.3.10#upgrades-from
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/24004
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/507
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/508
[5]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/120
[6]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/24005
[7]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/23920
[8]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/509
[9]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/122
[10]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/24006
[11]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/511

**Comment by wking** [comment]
4.2 -> 4.3.10 Azure failures are [a CPU shortage][1]; we might have to pull those edges.

Also, branch needs a rebase.

[1]: https://bugzilla.redhat.com/show_bug.cgi?id=1820432

**Comment by LalatenduMohanty** [comment]
> 4.2 -> 4.3.10 Azure failures are [a CPU shortage](https://bugzilla.redhat.com/show_bug.cgi?id=1820432); we might have to pull those edges.

We discussed and found that the bug is not an `upgrade blocker`.

**Comment by LalatenduMohanty** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1820778 is not an upgrade blocker. So this PR is good to go
/lgtm

**Comment by vrutkovs** [comment]
/hold cancel

errate is shipped, @eparis please approve

**Pull request merged**
