### PR TITLE
Update stable-4.15.yaml

### PR DESCRIPTION
**Pull request by SOLDIERz**
added openshift 4.14.43 to stable-4.15 channel

### CODE REVIEW

**Comment by sdodson** [comment]
Hi @SOLDIERz this will happen automatically once there's a 4.15.z version which can upgrade from 4.14.43. Since there's no such version this should wait. As such I'm going to go ahead and close this because the bots should take care of this once it's safe to do so.

/close

**Comment by SOLDIERz** [comment]
@sdodson Thank you so much for the Info. I didn't know this.

**Comment by SOLDIERz** [comment]
@sdodson There is already a new version of 4.15 which is 4.15.42. Is this version compatible with 4.14.43? Can I identify this somehow? Will there be an update soon? I'm at the moment stuck on 4.14.43.

**Comment by sdodson** [comment]
Yes, the release metadata includes the list of versions which can upgrade to that version.
```
$ oc adm release info 4.15.42 | grep 4.14.43
  Upgrades: 4.14.16, 4.14.17, 4.14.18, 4.14.19, 4.14.20, 4.14.21, 4.14.22, 4.14.23, 4.14.24, 4.14.25, 4.14.26, 4.14.27, 4.14.28, 4.14.29, 4.14.30, 4.14.31, 4.14.32, 4.14.33, 4.14.34, 4.14.35, 4.14.36, 4.14.37, 4.14.38, 4.14.39, 4.14.40, 4.14.41, 4.14.42, 4.14.43, 4.15.0, 4.15.2, 4.15.3, 4.15.5, 4.15.6, 4.15.7, 4.15.8, 4.15.9, 4.15.10, 4.15.11, 4.15.12, 4.15.13, 4.15.14, 4.15.15, 4.15.16, 4.15.17, 4.15.18, 4.15.19, 4.15.20, 4.15.21, 4.15.22, 4.15.23, 4.15.24, 4.15.25, 4.15.26, 4.15.27, 4.15.28, 4.15.29, 4.15.30, 4.15.31, 4.15.32, 4.15.33, 4.15.34, 4.15.35, 4.15.36, 4.15.37, 4.15.38, 4.15.39, 4.15.40, 4.15.41
```

**Pull request closed without merging**
