### PR TITLE
channels/stable-4.2: 4.2.20 to stable

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by vrutkovs** [comment]
/hold

Depends on https://github.com/openshift/cincinnati-graph-data/pull/67

**Comment by wking** [comment]
/hold

Blocked on fast in #67

**Comment by eparis** [comment]
/approve
/hold
but should it be in stable-4.3 as well?

**Comment by eparis** [comment]
/approve cancel
I think this should go into stable-4.3 at the same time (but only the amd64 version)

**Comment by LalatenduMohanty** [comment]
> I think this should go into stable-4.3 at the same time (but only the amd64 version)
The plan was to introduce 4.2 builds in stable-4.3 after 4.3.3 but now has blocker issues we have to wait for 4.3.5

**Pull request merged**
