### PR TITLE
OTA-1179: OWNERS: Grant sre-approvers root approval status

### PR DESCRIPTION
**Pull request by wking**
`cincinnati-graph-data-approvers` are not on-call, and update risks that impact the SRE-managed fleet may be discovered while no `cincinnati-graph-data-approvers` are available to declare them.  This pull request creates a new `sre-approvers` alias (populated with @openshift/openshift-team-sd-sre-team-leads) and grants root approval powers so they can:

* Update the `sre-approvers` alias in `OWNERS_ALIASES`, as described in 9982225f97.
* Manage update risks in `blocked-edges/`.
* Use `/override ...` comments in pull requests (which require root-directly approval powers) if needed to bypass any flaking CI and land emergency update risk declarations.

I'm not including `sre-approvers` as reviewers, because when `cincinnati-graph-data-approvers` are available, they'll handle review.  And when they are not available, `sre-approvers` will be driving an emergency response using internal communication channels, and will not need Prow/blunderbuss help in attracting reviewers.

I'm adding `OWNERS` to all the other child directories besides `blocked-edges`, because site reliability engineers will not need access to those locations.  By explicitly dropping them as approvers, Prow advice about relevant approvers will avoid pulling in SREs who are not interested in non-emergency repository activity.

### CODE REVIEW

**Comment by wking** [comment]
With OTA-1179, the time is now :)

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Comment by wking** [comment]
I've added b89be4b5 (and done a no-conflict rebase onto the branch tip) to [address][1]:

```
Verifying channel files are valid
Error: "/code/channels/OWNERS": is missing an extension
```


[1]: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_cincinnati-graph-data/3955/pull-ci-openshift-cincinnati-graph-data-master-e2e/1753098744288514048#1:build-log.txt%3A18-20

**Comment by LalatenduMohanty** [comment]
@wking can we merge these commits? I do not see the value of separate commits in this case.

**Pull request merged**
