### PR TITLE
candidate-4.2: add 4.2.20

### PR DESCRIPTION
**Pull request by thiagoalessio**

### CODE REVIEW

**Comment by eparis** [comment]
/approve
/hold
OTA please /lgtm when ready, but leave the /hold

**Comment by vrutkovs** [comment]
/lgtm

Added several more upgrade tests - all passed

**Comment by wking** [comment]
> Added several more upgrade tests - all passed

[* -> 4.2.20 CI updates][1] now have a number of runs for 4.1.34 and 4.2.19, but:

```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.2.20-x86_64 | grep Upgrades
  Upgrades: 4.1.34, 4.2.9, 4.2.10, 4.2.12, 4.2.13, 4.2.14, 4.2.15, 4.2.16, 4.2.18, 4.2.19
```

It's unlikely that the earlier 4.2.z differ from 4.2.19 enough to cause update issues, but I'd still like to test them.  Launching a few jobs...

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.2.20#upgrades-from

**Comment by wking** [comment]
Summarizing [* -> 4.2.20 CI updates][1]:

* Each baked in update source had at least one green CI run.
* 4.1.34 -> 4.2.20 is 4 for 4 passing.
* 4.2.* -> 4.2.20 shuffles through `aws`, `gcp`, and `azure,mirror` and all of them had at least some passing.
* [4.2.16 -> 4.2.20 failure][2] died on a CI-infra flake:

    ````
    ...the following tags from the release could not be imported to stable-initial after five minutes...
    ```

    4.2.16 -> 4.2.20 had [a successful AWS retry][3].
* [4.2.13 -> 4.2.20 failure][4] died on a different CI-infra flake:

    ```
    ...failed to acquire lease: resources not found
    ```

    4.2.13 -> 4.2.20 had [a successful AWS retry][5].
* [4.2.12 -> 4.2.20 failure][6] died on install:

    ```
    level=info msg="Waiting up to 30m0s for the cluster at https://api.ci-op-3k2xxbg1-7f637.ci.azure.devcluster.openshift.com:6443 to initialize..."
    level=fatal msg="failed to initialize the cluster: Cluster operator monitoring is reporting a failure: Failed to rollout the stack. Error: running task Updating Grafana failed: waiting for Grafana Route to become ready failed: waiting for RouteReady of grafana: the server is currently unable to handle the request (get routes.route.openshift.io grafana)" 
    ```

    so that's a 4.2.12 or infra issue, not a 4.2.12 -> 4.2.20 issue.  4.2.12 -> 4.2.20 had [a successful AWS retry][7].

So:

/lgtm

for candidate promotion.  Pull the hold whenever. 

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.2.20#upgrades-from
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18139
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18246
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18100
[5]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18130
[6]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/58
[7]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/18245

**Pull request merged**
