### PR TITLE
Cargo: update dependencies

### PR DESCRIPTION
**Pull request by vrutkovs**
* recent Cincinnati commit
* tokio 1.5
* lazy_static 1.4.0
* reqwest 0.11

Pinned actix-http and actix-service to be compatible with Cincinnati

See #752 for previous attempt

### CODE REVIEW

**Comment by wking** [comment]
Do we understand why this isn't hitting the #760 issue?  Your new pinning?

**Comment by vrutkovs** [comment]
> Do we understand why this isn't hitting the #760 issue? Your new pinning?

Yup, pins prevent from pulling in unexpected actix-* crates

**Review by wking — APPROVED** [review]
/lgtm

**Pull request merged**
