### PR TITLE
NO-JIRA: Release GA 4.17

### PR DESCRIPTION
**Pull request by DavidHurta**
internal-channels/fast.yaml: Force release 4.17.0 into fast

So that we can run the `hack/release-ga.sh` script to release GA 4.17

---

Release GA 4.17

Run by:
  $ ./hack/release-ga.sh 4.17

### CODE REVIEW

**Comment by DavidHurta** [comment]
/hold
I am not sure when exactly we want to merge this PR.

**Comment by DavidHurta** [comment]
I will rerun the command.

**Comment by DavidHurta** [comment]
I am clocking out. The edits are allowed for maintainers.

**Review by wking — APPROVED** [review]
[RHSA-2024:3718](https://access.redhat.com/errata/RHSA-2024:3718) is still 404ing for me, and it's not clear to me what the pipeline for that going live is.  But folks are saying 4.17.0 is shipped-live internally, and that's enough for me.

/lgtm

**Comment by wking** [comment]
For the future, API-driven way to decide when to release:

```console
$ curl -s 'https://access.redhat.com/product-life-cycles/api/v1/products?name=Openshift%20Container%20Platform%204' | jq -r '.data[].versions[] | select(.name == "4.17").type'
Full Support
```

Without merging these GA channels, the rendered https://console.redhat.com/openshift/releases shows a tile for the new 4.y, but is unable to look up the latest `stable-4.y` and `fast-4.y` releases to populate that tile.

**Pull request merged**
