### PR TITLE
Add 4.2.27 to fast

### PR DESCRIPTION
**Pull request by joepvd**

### CODE REVIEW

**Comment by wking** [comment]
/hold

Need #151 to land and cook first.

**Comment by wking** [comment]
[CI analysis][1]:

* 4.1.38 Success: 3 AWS.
* 4.2.15 Success: 1 GCP.
* 4.2.16 Success: 1 Azure.
* 4.2.18 Failed: 1 AWS ([died in setup][2])
* 4.2.19 Success: 1 GCP.
* 4.2.20 Success: 1 Azure.
* 4.2.21 Success: 1 AWS.
* 4.2.22 Success: 1 GCP.
* 4.2.23 Failed: 1 Azure ([CI registry flake][3]).
* 4.2.25 Failed: 1 AWS ([CI registry flake][4]).
* 4.2.26 Success: 1 AWS.  Failed: 1 GCP ([CI registry flake][5]).

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.2.27#upgrades-from
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/23999
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/119
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/24001
[5]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/506

**Comment by wking** [comment]
Also needs a rebase.

**Comment by wking** [comment]
Waiting on errata publication too.

**Comment by wking** [comment]
Replacement [CI][1] [jobs][2] [all][3] [passed][4].

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/24243
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/24243
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/526
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/24242

**Comment by LalatenduMohanty** [comment]
/hold for errata pushing

Currently there is no edge from 4.2.x to 4.3.x  and upgrades in 4.2 z stream to 4.2.27 looks good.

**Comment by wking** [comment]
Errata is live.

/hold cancel

**Comment by wking** [comment]
/retest

[Previous publish][1] flaked on Quay HTTP 429 (Too Many Requests).

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/pr-logs/pull/openshift_cincinnati-graph-data/150/pull-ci-openshift-cincinnati-graph-data-master-publish/308

**Pull request merged**
