### PR TITLE
Add 4.2.27 to stable

### PR DESCRIPTION
**Pull request by joepvd**

### CODE REVIEW

**Comment by wking** [comment]
/hold

Need #150 to land and cook first.

**Comment by wking** [comment]
Needs a rebase.

**Comment by wking** [comment]
#150 has cooked for over a day.  Still needs a rebase, but:

/hold cancel

**Comment by vrutkovs** [comment]
15 clusters updated from 4.1, 21 successful updates in z-stream

/lgtm

**Pull request merged**
