### PR TITLE
Add 4.2.23 to candidate

### PR DESCRIPTION
**Pull request by joepvd**

### CODE REVIEW

**Comment by wking** [comment]
[CI upgrades][1] currently just 4.1.37 and 4.2.22, not all of:

```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.2.23-x86_64 | grep Upgrades
  Upgrades: 4.1.31, 4.1.38, 4.2.12-s390x, 4.2.13-s390x, 4.2.14, 4.2.16, 4.2.18, 4.2.19, 4.2.20, 4.2.21, 4.2.22
```

I thought ART was planning on launching CI jobs for each baked-in edge (although s390x!?)?  I'll launch the missing jobs now...

[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.2.23#upgrades-from

**Comment by wking** [comment]
Hrm, 4.1.31 is also pretty old.  Are you sure we don't want to use 4.1.34 (the latest release in `stable-4.1`)?

**Comment by wking** [comment]
Launched tests by feeding cluster-bot:

```
test upgrade 4.1.31 4.2.23 aws
test upgrade 4.1.31 4.2.23 aws
test upgrade 4.1.38 4.2.23 aws
test upgrade 4.1.38 4.2.23 aws
test upgrade 4.2.14 4.2.23 gcp
test upgrade 4.2.16 4.2.23 azure,mirror
test upgrade 4.2.18 4.2.23 aws
test upgrade 4.2.19 4.2.23 gcp
test upgrade 4.2.20 4.2.23 azure,mirror
test upgrade 4.2.21 4.2.23 aws
test upgrade 4.2.22 4.2.23 gcp
```

Will see how those go.  [The][1] [four][2] [existing][3] [failures][4] were all release-build errors for 4.2.22 -> 4.2.23 on AWS (so CI cluster/registry flakes).

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/20978
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/20981
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/20982
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/20988

**Comment by sdodson** [comment]
> Hrm, 4.1.31 is also pretty old. Are you sure we don't want to use 4.1.34 (the latest release in `stable-4.1`)?

4.1.34 just went in yesterday, it probably wasn't in at the time the build was made.

**Comment by wking** [comment]
New CI jobs mostly passed, with only three failures:

* [Azure 4.2.16 -> 4.2.23][1] died on install (`level=fatal msg="failed to initialize the cluster: Working towards 4.2.16: 100% complete, waiting on authentication"`), so not an upgrade issue.  I've launched a replacement.
* [GCP 4.2.22 -> 4.2.23][2] died with `Cluster did not complete upgrade: timed out waiting for the condition: Could not update deployment "openshift-operator-lifecycle-manager/olm-operator" (323 of 432)`.  Not sure what's going on with that; I've launched a replacement.
* [AWS 4.1.38 -> 4.2.23][3] died on install (`aws_instance.master.1: Error waiting for instance (i-08bb57ff7032ba264) to become ready: timeout while waiting for state to become 'running' (last state: 'pending', timeout: 10m0s)`), no not an upgrade issue.  But [the other 4.1.38 -> 4.2.23][4] passed, so I'm not launching a replacement.

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/88
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/438
[3]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/21268
[4]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-aws-upgrade/21269

**Comment by wking** [comment]
The CI failure from the job I launched is [the only such failure in at least the past 24h][1].  And I'm personally not too worried about OLM, because it's far from the core, so I'm not going to dig further into that particular CI job.

[1]: https://search.svc.ci.openshift.org/?name=upgrade&search=Cluster%20did%20not%20complete%20upgrade:%20timed%20out%20waiting%20for%20the%20condition:%20Could%20not%20update%20deployment.*openshift-operator-lifecycle-manager/olm-operator

**Comment by wking** [comment]
Would be nice to see how [the][1] [two][2] pending CI jobs work out, but I'm not too worried, and this is just a candidate promotion, so:

/lgtm

[1]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-azure-upgrade/90
[2]: https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/441

**Comment by wking** [comment]
Oh, also, I haven't looked at 4.2.23 -> 4.3.*, but the `candidate-4.3` promotion here doesn't need update testing, because the latest 4.3 candidate links older 4.2 releases:

```console
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.3.5-x86_64 | grep Upgrades
  Upgrades: 4.2.21, 4.2.22, 4.3.0, 4.3.1, 4.3.2, 4.3.3
```

**Comment by wking** [comment]
> Would be nice to see how the two pending CI jobs work out...

And they both passed.

**Pull request merged**
